### PR TITLE
Policy 9 - Clarifications about copyright and collaborator ejection

### PR DESCRIPTION
**Pull request by Drapersniper**
Clarify parts that were not previously stated.

### CODE REVIEW

**Review by NeuroAssassin — APPROVED** [review]
Looks good to me.

**Review by TrustyJAID — APPROVED** [review]

**Review by aikaterna — DISMISSED** [review]

**Review by palmtree5 — DISMISSED** [review]

**Review by Jackenmen — DISMISSED** [review]

**Review by Kowlin — DISMISSED** [review]

**Review by Flame442 — DISMISSED** [review]

**Review by NeuroAssassin — CHANGES_REQUESTED** [review]
There should be a statement that describes what should happen in the event of an outside collaborator being removed, and what may come of the repository.

**Review by TrustyJAID — DISMISSED** [review]

**Review by Twentysix26 — DISMISSED** [review]
Approving the changes that have been made so far

**Review by palmtree5 — DISMISSED** [review]

**Review by TrustyJAID — DISMISSED** [review]

**Review by aikaterna — DISMISSED** [review]

**Review by NeuroAssassin — DISMISSED** [review]
Might want to specify how the vote will be called for ammendment 3 (ie under which policy and how the ruling is judged), however that part does not concern me.  Approving.

**Review by Jackenmen — APPROVED** [review]

**Pull request merged**
